import { router, json, requireAuth } from '@appdeploy/sdk';
import { secrets, db } from '@appdeploy/sdk';
const sessions=new Set<string>();
const adminToken=()=>`admin_${Date.now()}_${Math.random().toString(36).slice(2)}`;
async function validCode(code:unknown){try{const configured=await secrets.readSecret('PLEDGE_ADMIN_AUTH_CODE');return typeof code==='string'&&code===configured;}catch{return false;}}
function adminAuthorized(ctx:any){const body=ctx.body;const t=typeof body==='object'&&body!==null?body.token:ctx.query?.token;return typeof t==='string'&&sessions.has(t);}
async function audit(action:string,detail:string){await db.add('pledge_audit',[{action,detail,created_at:Date.now()}]);}
type AccountRecord={user_id:string;name:string;email:string;balance:number;invested:number;profit_earned:number;status:string;created_at:number;updated_at?:number};
async function ensureAccount(user:any){const table=`pledge_account_${user.userId}`;const {items}=await db.list<AccountRecord>(table,{limit:1});let account:AccountRecord&{id:string}=items[0] as AccountRecord&{id:string};if(!account){const record:AccountRecord={user_id:user.userId,name:user.name||'',email:user.email||'',balance:0,invested:0,profit_earned:0,status:'active',created_at:Date.now()};const [id]=await db.add(table,[record]);if(!id)throw new Error('Unable to create investor account');account={...record,id};}
const {items:globals}=await db.list<any>('pledge_investors',{limit:100});let global=globals.find((x:any)=>x.user_id===user.userId)||globals.find((x:any)=>x.email&&user.email&&String(x.email).toLowerCase()===String(user.email).toLowerCase());const globalRecord={investor_id:global?.investor_id||`PI-${user.userId.slice(0,8).toUpperCase()}`,user_id:user.userId,name:account.name||user.name||global?.name||'',email:account.email||user.email||global?.email||'',balance:Number(account.balance||0),invested:Number(account.invested||0),profit_earned:Number(account.profit_earned||0),status:account.status||global?.status||'active',created_at:account.created_at||global?.created_at||Date.now(),updated_at:Date.now()};if(global){await db.update('pledge_investors',[{id:global.id,record:globalRecord}]);}else{const [id]=await db.add('pledge_investors',[globalRecord]);if(!id)throw new Error('Unable to create shared investor record');global={...globalRecord,id};}
return {...account,global_id:global.id,investor_id:global.investor_id};}
export async function dailyInvestorProfit(){const {items}=await db.list<any>('pledge_settings',{limit:1});const s=items[0];const rate=Number(s?.dailyProfitRate||0);if(!s?.dailyProfitEnabled||rate<=0)return {statusCode:200,updated:0};const {items:users}=await db.list<any>('pledge_investors',{limit:100});let updated=0;for(const u of users){const invested=Number(u.invested||0);if(invested<=0||!u.user_id)continue;const profit=Number((invested*rate/100).toFixed(2));if(profit<=0)continue;const {items:accounts}=await db.list<any>(`pledge_account_${u.user_id}`,{limit:1});const account=accounts[0];if(!account?.id)continue;const next={...account,balance:Number(account.balance||0)+profit,profit_earned:Number(account.profit_earned||0)+profit,updated_at:Date.now()};const [ok]=await db.update(`pledge_account_${u.user_id}`,[{id:account.id,record:next}]);if(ok){await db.update('pledge_investors',[{id:u.id,record:{...u,balance:next.balance,profit_earned:next.profit_earned,updated_at:Date.now()}}]);await db.add(`pledge_transactions_${u.user_id}`,[{type:'Daily Profit',amount:profit,status:'Posted',reference:`${rate}% daily ledger accrual`,created_at:Date.now()}]);updated++;}}await audit('Daily profit applied',`${updated} investor accounts at ${rate}%`);return {statusCode:200,updated};}
export const handler=router({
'GET /api/_healthcheck':[async()=>json({message:'Success'})],
'POST /api/admin/login':[async({body})=>{if(!await validCode((body as any)?.code))return json({error:'Unauthorized'},401);const t=adminToken();sessions.add(t);await audit('Admin login','Administrator authenticated');return json({token:t});}],
'POST /api/admin/logout':[async({body})=>{if(typeof body==='object'&&body!==null)sessions.delete((body as any).token);return json({success:true});}],
'GET /api/me':[requireAuth(),async(ctx)=>json(await ensureAccount(ctx.user))],
'GET /api/me/summary':[requireAuth(),async(ctx)=>{const a=await ensureAccount(ctx.user);const {items:tx}=await db.list<any>(`pledge_transactions_${ctx.user!.userId}`,{limit:100});const investments=tx.filter((x:any)=>x.type==='Investment');const withdrawals=tx.filter((x:any)=>x.type==='Withdrawal');const deposits=tx.filter((x:any)=>x.type==='Deposit');const profits=tx.filter((x:any)=>x.type==='Daily Profit');return json({account:a,transactions:tx,investments,withdrawals,deposits,profitLoss:profits.reduce((s:any,x:any)=>s+Number(x.amount||0),0),referralEarnings:0,referrals:0});}],
'POST /api/me/invest':[requireAuth(),async(ctx)=>{const b=(ctx.body||{}) as any;const n=Number(b.amount);if(!Number.isFinite(n)||n<=0)return json({error:'Enter a valid positive amount'},400);const a=await ensureAccount(ctx.user);if(n>Number(a.balance||0))return json({error:'Insufficient wallet balance'},400);const next={...a,balance:Number(a.balance)-n,invested:Number(a.invested||0)+n,updated_at:Date.now()};const [ok]=await db.update(`pledge_account_${ctx.user!.userId}`,[{id:a.id,record:next}]);if(!ok)return json({error:'Unable to update account'},500);await db.add(`pledge_transactions_${ctx.user!.userId}`,[{type:'Investment',amount:n,status:'Active',reference:String(b.plan||'Investment plan'),created_at:Date.now()}]);const {items}=await db.list<any>('pledge_investors',{limit:100});const g=items.find((x:any)=>x.user_id===ctx.user!.userId);if(g)await db.update('pledge_investors',[{id:g.id,record:{...g,user_id:ctx.user!.userId,balance:next.balance,invested:next.invested,profit_earned:next.profit_earned||g.profit_earned,updated_at:Date.now()}}]);return json({success:true,account:next});}],
'POST /api/me/withdraw':[requireAuth(),async(ctx)=>{const b=(ctx.body||{}) as any;const n=Number(b.amount);if(!Number.isFinite(n)||n<=0)return json({error:'Enter a valid positive amount'},400);const a=await ensureAccount(ctx.user);if(n>Number(a.balance||0))return json({error:'Insufficient wallet balance'},400);await db.add(`pledge_transactions_${ctx.user!.userId}`,[{type:'Withdrawal',amount:n,status:'Pending',reference:String(b.reference||'Withdrawal request'),created_at:Date.now()}]);return json({success:true,message:'Withdrawal request submitted for administrator review.'});}],
'POST /api/public/deposit-request':[async({body})=>{const b=(body||{}) as any;const n=Number(b.amount);if(!b.name||!b.email||!b.txHash||!Number.isFinite(n)||n<=0)return json({error:'Name, email, amount and transaction hash are required'},400);const [id]=await db.add('pledge_deposit_requests',[{name:String(b.name),email:String(b.email),amount:n,tx_hash:String(b.txHash),network:String(b.network||''),status:'Pending',created_at:Date.now()}]);return json({success:true,id});}],
'GET /api/public/deposit-settings':[async()=>{const {items}=await db.list<any>('pledge_settings',{limit:1});return json(items[0]||{network:'',address:'',memo:'',asset:'USDT',dailyProfitRate:0,dailyProfitEnabled:false});}],
'GET /api/admin/overview':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const [u,d,t]=await Promise.all([db.list('pledge_investors',{limit:100}),db.list('pledge_deposit_requests',{limit:100}),db.list('pledge_transactions',{limit:100})]);return json({users:u.items.length,activeInvestors:u.items.filter((x:any)=>x.status!=='inactive').length,portfolioValue:u.items.reduce((s:any,x:any)=>s+Number(x.balance||0)+Number(x.invested||0),0),investments:t.items.filter((x:any)=>x.type==='Investment').length,pendingDeposits:d.items.filter((x:any)=>x.status==='Pending').length,pendingWithdrawals:t.items.filter((x:any)=>x.type==='Withdrawal'&&x.status==='Pending').length,referrals:0,supportOpen:0});}],
'GET /api/admin/investors':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const r=await db.list<any>('pledge_investors',{limit:100});return json({items:r.items,nextToken:r.nextToken});}],
'GET /api/admin/users':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const r=await db.list<any>('pledge_investors',{limit:100});return json({items:r.items,nextToken:r.nextToken});}],
'GET /api/admin/users/:id':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const [u]=await db.get<any>('pledge_investors',[ctx.params.id]);if(!u)return json({error:'User not found'},404);return json(u);}],
'PUT /api/admin/users/:id':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const [u]=await db.get<any>('pledge_investors',[ctx.params.id]);if(!u)return json({error:'User not found'},404);const b=(ctx.body||{}) as any;const next={...u,name:b.name===undefined?u.name:String(b.name),email:b.email===undefined?u.email:String(b.email),status:b.status===undefined?u.status:String(b.status),updated_at:Date.now()};const [ok]=await db.update('pledge_investors',[{id:u.id,record:next}]);if(!ok)return json({error:'Unable to update user'},500);if(u.user_id){const {items}=await db.list<any>(`pledge_account_${u.user_id}`,{limit:1});const a=items[0];if(a){const [accountOk]=await db.update(`pledge_account_${u.user_id}`,[{id:a.id,record:{...a,name:next.name,email:next.email,status:next.status,updated_at:Date.now()}}]);if(!accountOk)return json({error:'User updated but account synchronization failed'},500);}}await audit('Investor updated',`${next.investor_id} · ${next.email}`);return json(next);}],
'DELETE /api/admin/users/:id':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const [u]=await db.get<any>('pledge_investors',[ctx.params.id]);if(!u)return json({error:'User not found'},404);const [ok]=await db.delete('pledge_investors',[u.id]);if(!ok)return json({error:'Unable to delete user'},500);await audit('Investor deleted',`${u.investor_id} · ${u.email}`);return json({success:true,id:u.id});}],
'POST /api/admin/investors':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const b=(ctx.body||{}) as any;if(!b.name||!b.email)return json({error:'Name and email are required'},400);const [id]=await db.add('pledge_investors',[{investor_id:`PI-${Date.now().toString(36).toUpperCase()}`,name:String(b.name),email:String(b.email),balance:0,invested:0,profit_earned:0,status:'active',created_at:Date.now()}]);return json({id});}],
'POST /api/admin/investors/:id/credit':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const b=(ctx.body||{}) as any;const n=Number(b.amount);if(!Number.isFinite(n)||n<=0)return json({error:'Enter a valid positive amount'},400);const [u]=await db.get<any>('pledge_investors',[ctx.params.id]);if(!u)return json({error:'Investor not found'},404);const next={...u,balance:Number(u.balance||0)+n,updated_at:Date.now()};const [ok]=await db.update('pledge_investors',[{id:u.id,record:next}]);if(!ok)return json({error:'Unable to update investor'},500);if(u.user_id){const {items}=await db.list<any>(`pledge_account_${u.user_id}`,{limit:1});const a=items[0];if(a)await db.update(`pledge_account_${u.user_id}`,[{id:a.id,record:{...a,balance:next.balance,invested:Number(a.invested||0),profit_earned:Number(a.profit_earned||0),updated_at:Date.now()}}]);}await db.add('pledge_transactions',[{investor_id:u.investor_id,user_id:u.user_id||'',type:'Deposit',amount:n,status:'Completed',reference:String(b.reference||'Admin credit'),created_at:Date.now()}]);await audit('Manual wallet credit',`${u.investor_id} +${n}`);return json({success:true,balance:next.balance});}],
'GET /api/admin/deposits':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);return json(await db.list('pledge_deposit_requests',{limit:100}));}],
'POST /api/admin/deposits/:id/approve':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const [d]=await db.get<any>('pledge_deposit_requests',[ctx.params.id]);if(!d||d.status!=='Pending')return json({error:'Pending deposit request not found'},404);const {items}=await db.list<any>('pledge_investors',{limit:100});const u=items.find((x:any)=>x.email===d.email);if(!u)return json({error:'No investor account matches this email'},404);const [ok]=await db.update('pledge_deposit_requests',[{id:d.id,record:{...d,status:'Approved',reviewed_at:Date.now()}}]);if(!ok)return json({error:'Unable to approve deposit'},500);const next={...u,balance:Number(u.balance||0)+Number(d.amount),updated_at:Date.now()};await db.update('pledge_investors',[{id:u.id,record:next}]);if(u.user_id){const {items:accounts}=await db.list<any>(`pledge_account_${u.user_id}`,{limit:1});const a=accounts[0];if(a)await db.update(`pledge_account_${u.user_id}`,[{id:a.id,record:{...a,balance:Number(a.balance||0)+Number(d.amount),updated_at:Date.now()}}]);}await db.add('pledge_transactions',[{investor_id:u.investor_id,user_id:u.user_id||'',type:'Deposit',amount:Number(d.amount),status:'Completed',reference:d.tx_hash,created_at:Date.now()}]);await audit('Deposit approved',`${u.investor_id} +${d.amount}`);return json({success:true,balance:next.balance});}],
'GET /api/admin/settings':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const {items}=await db.list<any>('pledge_settings',{limit:1});return json(items[0]||{network:'',address:'',memo:'',asset:'USDT',dailyProfitRate:0,dailyProfitEnabled:false});}],
'PUT /api/admin/settings/deposit':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);const b=(ctx.body||{}) as any;const {items}=await db.list<any>('pledge_settings',{limit:1});const rate=Math.max(0,Math.min(100,Number(b.dailyProfitRate||0)));const record={network:String(b.network||''),address:String(b.address||''),memo:String(b.memo||''),asset:String(b.asset||'USDT'),dailyProfitRate:rate,dailyProfitEnabled:Boolean(b.dailyProfitEnabled),updated_at:Date.now()};if(items[0])await db.update('pledge_settings',[{id:items[0].id,record}]);else await db.add('pledge_settings',[record]);await audit('Website/profit settings updated',`${record.asset} · ${record.network} · ${rate}% daily · ${record.dailyProfitEnabled?'enabled':'disabled'}`);return json({success:true,...record});}],
'POST /api/admin/profit/apply':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);return json(await dailyInvestorProfit());}],
'GET /api/admin/audit':[async(ctx)=>{if(!adminAuthorized(ctx))return json({error:'Unauthorized'},401);return json(await db.list('pledge_audit',{limit:100}));}],
});
